### ISSUE TITLE
Wrong type for annotSV conversion

### ISSUE THREAD

**Issue by gevro** [SamuelNicaise/variantconvert#27]
Hi,
The new AnnotSV VCF output format has an issue -- many numeric fields are being given Type=String. This breaks downstream pipelines that then do not allow proper numeric type filtering on "String" fields.

For example:
##INFO=<ID=B_inv_AFmax,Number=1,Type=String...
##INFO=<ID=B_gain_AFmax,Number=1,Type=String...

Can you please fix this?

Thanks

**Comment by SamuelNicaise** [comment]
Hi gevro, thanks for using this tool. This is due to the conservation of "split" annotations (see the Annotation_mode column in AnnotSV) in the output VCF. This leads to most annotations having a format such as "annot1|annot2|annot3" which is a String. 

I am implementing a different way to keep the "split" annotation data in order to make downstream analysis easier. 

The next version of variantconvert will be included in the next version of AnnotSV.

**Comment by gevro** [comment]
Thank you. When will the next version of these tools be available approximately?

**Comment by SamuelNicaise** [comment]
The next version of variantconvert should be available in this repository this month. I don't know regarding AnnotSV.

**Comment by gevro** [comment]
Hello, Has this issue been updated / addressed yet?
Thanks!

**Comment by SamuelNicaise** [comment]
Hi, 
A fix is in the works but I haven't been able to put in the time to finish it for now. 
I expect it to be available by the end of the year at worst. Sorry to keep you waiting.

**Comment by gevro** [comment]
Thank you

**Comment by gevro** [comment]
Hi, I'm curious if this is still in progress? Thanks!

**Comment by SamuelNicaise** [comment]
Hi, thank you for your renewed patience! Yes the new version will be released very soon, your fix in particular was pushed yesterday to the release branch (pypi).

The new version gives up on the "full|split annot 1|split annot2..." INFO format that forced all annotations to be a String. 

There are two possibilities instead (custom choice in config): 
- keep only the "full" annotation
- "full" annotation + one additional variant line in the output VCF per "split" annotation

With this each annotation has its expected type.

**Comment by gevro** [comment]
Hi, Has the new version been released yet?

**Comment by gevro** [comment]
Hello, Just checking again if any update?

**Comment by gevro** [comment]
Hello, Will this issue be fixed? Without a fix, variantconvert cannot be used for annotSV.

Thanks

**Comment by SamuelNicaise** [comment]
Hi, 

Thanks again for your continued feedback. This was eventually fixed in the new 2.0.0 release. Along with the new modes aforementioned modes above, the default conversion mode ("combined") that keeps all annotations as one line per variant also has proper types now. 

When all annotations in a list are identical, they are also merged as one to facilitate filtering now. 

If the list format is an issue for filtering, I recommend using one of the new conversion modes ("full" or "full&split"). I will leave this issue open for some time in case you have other related questions or comments.

Best,

**Comment by lgmgeo** [comment]
[AnnotSV 3.4.1](https://github.com/lgmgeo/AnnotSV) is posted with an updated version of variantconvert (v2.0.1).

The [variantconvert conversion mode](https://github.com/SamuelNicaise/variantconvert/?tab=readme-ov-file#alternative-modes) can be set by the user in AnnotSV (see the -variantconvertMode options).
Instead of combining all full and split annotations (default mode: combined), variantconvert can represent each full or split annotation on one line (mode: full&split), or only "full" annotation can be kept (mode: full). 

Regarding on your needs, please set the `-variantconvertMode`option to `full` or `fullsplit`.

Can you confirm that this fixes your bug?

**Comment by lgmgeo** [comment]
Any news?

**Comment by gevro** [comment]
We will test it in a few days.
